1920 수 찾기 자바 반영
hyunjinkim-kr/algorithm pull request #18
Opened 2024-10-20 08:38 UTC by hyunjinkim-kr

## 문제
- 수 찾기
- https://www.acmicpc.net/problem/1920

## 해결책
- 주어진 범위의 배열을 정렬한 후, 찾을 수를 배열에서 이진탐색을 통해 검색한다.

### 세부 사항
1. **변수 설명**: 문제에서 사용된 주요 변수와 입력 데이터에 대해 설명합니다.
 - N : 숫자를 찾을 배열의 길이
 - arr1 : N개의 숫자가 저장된 배열
 - M : 탐색할 숫자의 개수
 - target : M번 입력중 배열에 있는지 체크할 숫자
 - resultArr : M번 주어진 숫자가 N배열에 있는지 1과 0으로 저장된 배열
 - start : arr1을 탐색할 시작 범위
 - end : arr1을 탐색할 끝 범위
 - mid : start 와 end를 더하고 2로 나눈 값

## 알고리즘 설명
1. N과 N번 입력받은 숫자를 arr1에 저장한다.
2. arr1을 정렬한다.
 - 복잡도 : N log N
3. M을 입력받고, M번 숫자를 입력받으며 각각 arr1에 존재하는지 체크하고 저장한다.
 - 3-1. start 를 0, end를 arr1의 크기로 탐색을 시작한다.
 - 3-2. start 가 end보다 큰 경우, 0을 반환한다(범위 벗어남, target 없음)
 - 3-3. arr1의 mid 값이 target과 일치하면 1을 반환한다.
 - 3-4. arr1의 mid 값이 target 보다 큰 경우, start ~ mid -1 범위로 재귀한다.
 - 3-5. " 작은경우, mid + 1 ~ end 범위로 재귀한다.
 - 복잡도 : log N

## 시간복잡도
- O(NlogN)

2024-10-20 14:25 UTC, kyeongmincho requested changes
> 변수 설명: 문제에서 사용된 주요 변수와 입력 데이터에 대해 설명합니다.

이런 말은 없어도 됨

> arr1을 정렬한다.

존재만 찾으면 되는데 왜 굳이 정렬하고 이진탐색을?

2024-10-21 11:05 UTC, kyeongmincho commented
> set에 저장한다

꼭 저장해야 하는지?

2024-10-23 06:45 UTC, hyunjinkim-kr commented
> > set에 저장한다
> 
> 꼭 저장해야 하는지?

이해가 잘 되지 않음. 
1. 기존에 입력된 숫자들을 저장한채로 (여기서 Set 에 N번 입력받은 숫자를 저장) 
2. 존재여부를 확인할 숫자를 탐색해야 맞는게 아닌지?

2024-10-24 11:19 UTC, kyeongmincho requested changes

2024-10-24 11:19 UTC, kyeongmincho commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +  public static String solve(StringTokenizer st1, Integer n, Integer target) {
이게 효율적인 건 맞는데, `solve()`라는 함수가 토크나이저라는 파라미터를 두는 건 이상한 듯.
n 개의 정수가 주어지는 거니까 토크나이저 대신 `ArrayList<Integer>`가 파라미터로 오는 게 자연스러워 보임.
앞으로도
1. 문제에서 주어지는 입력을 잘 추상화하여 `solve()`의 타입을 먼저 올바르게 설정하고
1. 그 뒤에 입력 등의 전처리를 작성하도록 하자

2024-10-24 11:19 UTC, kyeongmincho commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +  // -- 시간복잡도 O(M * N)
`N`은 사실 단순 테스트 케이스 개수니까 굳이 솔루션이나 복잡도에 넣지 말자

2024-10-25 06:14 UTC, hyunjinkim-kr commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +  public static String solve(StringTokenizer st1, Integer n, Integer target) {
ArrayList 혹은 collections를 이용한 처리시, 시간초과 나타남.

2024-10-27 08:51 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
solve 함수로 뭉뚱그리지 말고
1. List<Integer> haystack, List<Integer> needles 로 각각 입력받은 리스트 만들고
2. Boolean contains(HashSet<Integer> haystackSet, Integer needle)
3. 출력은 하나씩 하든가, needles.stream().map(l -> contains(haystackSet, l).map(l -> l ? "1" : "0").toList() 등으로 한줄로 하든가 하는게 형태가 괜찮을듯

2024-10-27 08:51 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
아니잠깐 이거 왜 ArrayList에서 contains를 하냐?

2024-10-27 08:51 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
자바 Collections 자료구조별로
1. add
2. update
3. delete
4. contains
시간복잡도 전부 다시생각해봐라.

2024-10-27 08:51 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
첫 코멘트는 무시해라. 리턴형이 String이라 답 전체를 리턴하는줄알았음.

Boolean을 리턴하게 하고
출력부에서 T / F에 따라 값을 만들어내라.

2024-10-27 08:51 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
ArrayList라고 해도, 원소 개수인 n은 절대 받을 필요가 없을텐데 왜 받는지 의문이다.

2024-10-27 08:51 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
그냥 니 코드에는 중대한 2개의 결함이 있음
1. 선형 자료구조에서의 '찾기'연산은 O(N)임. 이 연산은 없다고 생각해야함.
2. 이미 ArrayList<Integer>를 solve 함수에서 받는데, 그 개수인 무의미한 n은 왜 받냐

2024-10-27 09:12 UTC, kyeongmincho commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> 선형 자료구조에서의 '찾기'연산은 O(N)임. 이 연산은 없다고 생각해야함.

무슨 말?

2024-10-27 09:13 UTC, kyeongmincho commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +  public static String solve(ArrayList<Integer> numArr, Integer n, Integer target) {
반환형은 boolean

2024-10-27 11:46 UTC, iyaacs requested changes

2024-10-27 11:46 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +  public static Boolean exists(HashSet<Integer> chkSet, Integer target) {
본질적으로 이 함수는
return chkSet.contains(target); 으로 단순화 가능하고
더 나아가서, 애초에 만들 필요가 없다.

2024-10-27 11:50 UTC, iyaacs requested changes

2024-10-27 11:50 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +        resultArr.add(exists(set, target));
더 나아간다면

bw.write(chkSet.contains(target) ? "1": "0" + "\n"); 가능할듯

2024-10-27 11:51 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +        resultArr.add(exists(set, target));
이렇게 하는이유 -> 이문제인지 다른문제인지 말했던것같은데
쓰는 입장에서 나중에 이걸 비동기로 처리한다면
모든 contains가 끝나기 기다리기보다
하나씩 우다다 나오는게 쓰기좋음

2024-10-27 12:06 UTC, iyaacs approved these changes

2024-10-27 12:06 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +package binarySearch;
마지막으로. 패키지명 불-편.

이것만 바꾸면 Merge를 허한다.

2024-10-27 12:08 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +        bw.write(set.contains(target) ? "1" + "\n" : "0" + "\n");
진짜 몰라서 그러는데 이거 에러나냐?
bw.write((set.contains(target) ? "1"  : "0") + "\n");

내 코드(아래)가 그래도 니거보다는 나은듯.
+"\n" 두번하는거 짜쳐
bw.write(set.contains(target) ? "1"  : "0"); 
bw.write("\n");

2024-10-27 12:11 UTC, hyunjinkim-kr commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +        bw.write(set.contains(target) ? "1" + "\n" : "0" + "\n");
반영 완료 -> bw.write(set.contains(target) ? "1" + "\n" : "0" + "\n"));

2024-10-27 13:53 UTC, kyeongmincho requested changes

2024-10-27 13:53 UTC, kyeongmincho commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +      HashSet<Integer> set = new HashSet();
`main()`에 때려박는 거 @iyaacs 의 주문인가??

나는 이 리포에서 전반적으로 입출력-agnositc 한 코드를 짰으면 좋겠음
- 입출력 부분과 실질적 문제를 명시적으로 구분(e.g. `main()`과 `solve()`)하고 (마치 시중의 "코테 플랫폼"처럼...)
- `solve()` 혹은 그 안에서 사용되는 서브 루틴들의 타입을 잘 주는 훈련을 했으면 함

예를 들어, 이 문제의 입력을 추상화하면 solve 함수 타입은 아래와 같을 거임 (몇 개의 수가 주어지는지는 생략):
`solve(list<int>, list<int>) -> list<bool>`
그리곤 `solve()` 안에서 hash set을 사용하여...

@iyaacs @hyunjinkim-kr  어떻게 생각하는지?

2024-10-27 16:30 UTC, iyaacs commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +      HashSet<Integer> set = new HashSet();
콘솔 입출력의 제한? 인듯 한데
solve(list<int>, list<int>) -> list<bool> 보다는
solve(list<int>, int) -> bool 인게 낫지 않을까함.

list<int>를 전부 만들어서 주는경우에 모든 list가 다 입력된 이후, contains가 전부 수행된 이후 마지막 결과가 나오는 형태일텐데

나중에 골이 async를 쓴다고 가정하면
async int contains(list<int> arr, int target)
이걸 갖다쓰는곳에서
await contains(arr, target)으로 쓸수있기때문에 웬만하면 이런 경우에는 하나씩 나오는것도 훈련했으면 하는 바람이긴 함.

2024-10-28 00:28 UTC, kyeongmincho commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +      HashSet<Integer> set = new HashSet();
ㅇㅇ 그 말이었음.
- 답안지의 템플릿으로서 solve(list<int>, list<int>) -> list<bool>  는 유지했으면 좋겠고
- 니가 말한 (좀 더 semantic한 이름을 주어) contains(list, int) -> bool 를 solve에서 호출하게끔ㅇㅇ

2024-10-28 09:36 UTC, hyunjinkim-kr commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +      HashSet<Integer> set = new HashSet();
exist(chkArr, targetArr) 함수에서 set을 활용해 resultArr을 받아 출력하도록 수정함.

2024-10-28 10:16 UTC, kyeongmincho approved these changes

2024-10-28 10:16 UTC, kyeongmincho commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +  public static ArrayList<Boolean> exists(ArrayList<Integer> chkArr, ArrayList<Integer> targetArr) {
`solve`로 이름 바꾸자. (https://github.com/hyunjinkim-kr/algorithm/pull/19#discussion_r1818105863 코멘트 참고)
이것만 바꾸면 LGTM

2024-10-29 03:51 UTC, hyunjinkim-kr commented on java-algorithms/step-by-step/binarySearch/Solve1920.java
> +  public static ArrayList<Boolean> exists(ArrayList<Integer> chkArr, ArrayList<Integer> targetArr) {
exists ->> solve 라는 이름으로만 바꾸고 반영

2024-10-29 03:55 UTC, merged